language: rust
rust:
- stable
- beta
- nightly
deploy:
  provider: cargo
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: KM+CYq7/iCZ53oQjiLU60zqbcKzEM/zm22MOlCPizkYiDFrjbkDcluPYPVnvZWeWDUNbWX6H2AwFifwsY7TP4QzmS3F8aQWsvPanqr8Ztj8zbaZdOrGN7NDxhGh+t2kMJE2DarGHz9IU0+jXjYBK2zwdXOY4urn4Zuqz3G+CMERPDfF62Irzpht6qK+Q1d/hbw09h4QM2Oqu3+MnuhQUfn+Qsieqv6N3KODpHRLYsa18ddh+XNzhgES9obmfmdcpKn0GNtGggigBVgCsSWZv+gkz4ei9CqtG9LS+AD5Uz6GwNTRCjmHBZvGKu8vtSuU1lPuTUFaF6mH+s42dzyQU7dZtUBFVW4leB51GlXl/Rdv/Y5XPAFid50+DRcH8P1ax5SaLAeT4T8TISQcJHtIlruCwp4khufBsz8+Kkv7UeMfeM2EcigQFU3K9sFYMY+ebYfnteoCQQ2JXwj1CJ2f3m4vuBAD4aV3M3BsplyX0Ycvo/SqiMeWDoakVBp7yjSTyb/UvbPeHkD93EoyzRgNO7HziTq1ioNF204USw2NbxnZRFQqGEo6/wXboOhEKwChr5Swoa8OJkH3b0sOh82SwjHzVGZOXr7Mw9vGSxNp3tw+d6xI1tciWVvshdygvX0ubuDF7kke9qHqQ9jtiwAYFFSVsedZ9lEsk+N9ntQ1cq4g=
branches:
  only:
  - master
cache: cargo
script:
- cargo build --verbose
- cargo test --verbose
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - language: rust
    rust: stable
    name: check wasm32 support
    install: rustup target add wasm32-unknown-unknown
    script: cargo check --target wasm32-unknown-unknown
